# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: 亚雄的博客
SEOTitle: Jingming(Yaxiong)的博客 | Yaxiong Blog
keyword: "jingming的博客, jingming, cili, micili, C++, leetcode, 音乐, 圣经, Yaxiong"
header-img: img/post-bg-desk.jpg
email: jingminglake@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jingminglake.github.io" # the base hostname & protocol for your site, e.g. https://example.com
#twitter_username: jekyllrb
github_username:  jingminglake


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Unless a grain of wheat falls into the ground and dies, it remains alone; but if it dies, it produces much grain."
sidebar-avatar: /img/about-me.png

# Build settings
theme: minima
remote_theme: pages-themes/architect@v0.2.0
#remote_theme: pages-themes/hacker@v0.2.0
#plugins:
#  - jekyll-feed

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 评论系统
# Disqus（https://disqus.com/）
disqus_username: jingming

# Google Analytics
ga_track_id: 'UA-150811080-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
